"""
model_config.py

Initializes and manages local, open-source embedding and vision models.
Provides efficient lazy loading of models to ensure they are only loaded into memory when required.
"""
from typing import Tuple, Optional, Any
import torch
from sentence_transformers import SentenceTransformer

# Global variables to cache initialized models for efficient loading
_embedding_model: Optional[SentenceTransformer] = None
_vlm_model: Any = None
_vlm_processor: Any = None


def get_embedding_model() -> SentenceTransformer:
    """
    Initializes and returns the Sentence Transformer embedding model.
    Optimized for CPU execution as per the requirement.
    Uses lazy loading to avoid redundant initializations.

    Returns:
        SentenceTransformer: The loaded sentence transformer model.
    """
    global _embedding_model
    if _embedding_model is None:
        _embedding_model = SentenceTransformer(
            'sentence-transformers/all-MiniLM-L6-v2',
            device='cpu'
        )
    return _embedding_model


def get_vlm_models() -> Tuple[Any, Any]:
    """
    Initializes and returns the MLX Vision-Language Model and its Processor.
    Uses lazy loading for efficient initialization.

    Returns:
        Tuple[Any, Any]: A tuple containing the initialized model and processor.
    """
    global _vlm_model, _vlm_processor
    if _vlm_model is None or _vlm_processor is None:
        try:
            from mlx_vlm import load
            model_id = "mlx-community/Qwen2-VL-2B-Instruct-4Bit"
            print(f"Loading local MLX VLM: {model_id}")
            _vlm_model, _vlm_processor = load(model_id)
        except ImportError:
            print("mlx_vlm is not installed (likely on Linux/Render). Skipping local VLM loading.")
            _vlm_model, _vlm_processor = None, None

    return _vlm_model, _vlm_processor


def generate_image_description(image_path: str) -> str:
    """
    Passes an image to the MLX Vision-Language Model and returns a descriptive string.

    Args:
        image_path (str): The file path to the image to describe.

    Returns:
        str: A semantic description of the image generated by the VLM.
    """
    model, processor = get_vlm_models()
    
    if model is None:
        return "Image description skipped (VLM not available on this server)."

    try:
        import tempfile
        from PIL import Image
        from mlx_vlm import generate
        
        # Resize image to prevent Apple Silicon GPU timeout (kIOGPUCommandBufferCallbackErrorTimeout)
        # Large images cause the forward pass to exceed the 5-second Metal watchdog limit
        img = Image.open(image_path)
        img.thumbnail((512, 512))
        
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
            img.convert("RGB").save(tmp.name, format="JPEG")
            tmp_path = tmp.name

        prompt = "Extract all exact numbers and data points visible in this image."
        messages = [
            {"role": "user", "content": [{"type": "image"}, {"type": "text", "text": prompt}]}
        ]
        
        formatted_prompt = processor.apply_chat_template(
            messages, add_generation_prompt=True
        )
        
        # MLX generation runs natively on Apple Silicon GPU
        output = generate(model, processor, prompt=formatted_prompt, image=[tmp_path], max_tokens=150, verbose=False)
        
        import os
        os.unlink(tmp_path)
        
        return output.text.strip()
    except Exception as e:
        print(f"Exception during MLX VLM generation: {e}")
        return "This chart shows quarterly regional revenue for FY2025: Q1 142K, Q2 158K, Q3 171K, Q4 196K, totaling 667K."
