"""
qa_generator.py

Generates grounded, explainable answers using the Groq API (Llama 3) based on the 
retrieved Graph-Augmented RAG context. Parses inline citations for full traceability.
"""

import re
import logging
import json
from typing import Dict, List, Any
from groq import Groq

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

# Regular expression to extract inline citations in the format [ID: <uuid>]
CITATION_PATTERN = re.compile(r"\[ID:\s*([^\]]+)\]")


def generate_answer(query: str, context_str: str) -> Dict[str, Any]:
    """
    Passes the retrieved context and user query to a Groq LLM to generate an answer.
    Extracts all cited IDs from the output to provide graph traceability.

    Args:
        query (str): The user's natural language question.
        context_str (str): The formatted context blocks returned by the retriever.

    Returns:
        Dict[str, Any]: A dictionary containing:
            - 'answer': The raw string answer generated by the LLM.
            - 'cited_ids': A list of extracted source ID strings.
    """
    logger.info(f"Generating QA response for query: '{query}'")

    system_prompt = (
        "You are a highly skilled, strict document analyst. Your task is to answer the user's "
        "question using ONLY the provided context blocks.\n\n"
        "RULES:\n"
        "1. GROUNDING: You MUST NOT use outside knowledge or hallucinate information. If the "
        "provided context does not contain the information needed to answer, you must explicitly "
        "state: 'I cannot answer this based on the provided context.'\n"
        "2. INLINE PER-SENTENCE CITATION: You MUST emit a citation tag `[ID: {id}]` immediately after "
        "EVERY distinct claim, number, or sentence. Do NOT wait until the end of the paragraph or "
        "answer to list citations.\n"
        "3. MULTI-SOURCE GRANULARITY: If an answer synthesizes information from multiple sources "
        "(e.g., a table AND a chart), you MUST place the specific citation tag immediately after the "
        "specific clause or number it supports. Do NOT collapse them into a single ID at the end of "
        "the sentence. Each distinct fact MUST cite its MOST PRIMARY source.\n"
        "4. DECOMPOSE: When the question involves cross-referencing, explicitly state which specific "
        "source each number comes from, and place the tag right next to that number.\n"
        "5. Keep your answer concise, objective, and directly address the user's query.\n\n"
        "EXAMPLE OF GOOD CITATION:\n"
        "The total revenue for Q3 was $158K [ID: image-uuid-123], while the APAC region contributed "
        "$45K according to the financial summary [ID: table-uuid-456]."
    )

    user_message = (
        f"Provided Context:\n"
        f"---\n"
        f"{context_str}\n"
        f"---\n\n"
        f"Question: {query}\n"
    )

    try:
        # Initialize Groq client. Expects GROQ_API_KEY environment variable to be set.
        client = Groq()

        # Call the llama-3.3-70b-versatile model via Groq's chat completion endpoint
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message}
            ],
            temperature=0.0, # Zero temperature enforces strict analytical grounding
            max_tokens=1024,
        )

        # Extract the raw text answer from the LLM
        answer_text = completion.choices[0].message.content

        # Extract all cited UUIDs using our regex pattern
        cited_ids: List[str] = CITATION_PATTERN.findall(answer_text)
        
        # Deduplicate the cited IDs while preserving the order they were referenced
        cited_ids = list(dict.fromkeys(cited_ids))

        # Remove the raw citation tags from the text so they don't appear in the UI
        clean_answer_text = re.sub(r"\s*\[ID:\s*([^\]]+)\]", "", answer_text).strip()

        return {
            "answer": clean_answer_text,
            "cited_ids": cited_ids
        }

    except Exception as e:
        logger.error(f"Failed to generate answer from Groq API: {e}")
        # Graceful fallback dictionary in case of timeouts, rate limits, or auth failures
        return {
            "answer": "An error occurred while communicating with the LLM API. Please check your connection or API key and try again later.",
            "cited_ids": []
        }

def generate_document_summary(text_content: str) -> Dict[str, Any]:
    """
    Generates a high-level summary, key highlights, and main entities from the document text.
    """
    logger.info("Generating document summary via Groq...")
    
    system_prompt = (
        "You are an expert document summarizer. Given the text from a document, "
        "provide a JSON output with the exact following keys:\n"
        '1. "summary": A brief 1-2 sentence high-level summary of the document.\n'
        '2. "highlights": A list of exactly 3 key takeaways or important bullet points.\n'
        '3. "entities": A list of 3 to 5 main entities, concepts, or topics discussed.\n'
        "You MUST output valid JSON only."
    )
    
    try:
        client = Groq()
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                # Truncate to first ~15,000 characters to ensure we fit in context window easily
                {"role": "user", "content": text_content[:15000]}
            ],
            temperature=0.1,
            max_tokens=512,
            response_format={"type": "json_object"}
        )
        
        response_text = completion.choices[0].message.content
        return json.loads(response_text)
        
    except Exception as e:
        logger.error(f"Failed to generate summary from Groq API: {e}")
        return {
            "summary": "Summary generation failed. Please ensure GROQ_API_KEY is set.",
            "highlights": ["Could not generate highlights"],
            "entities": ["Unknown"]
        }
