from typing import Tuple
from uuid import UUID
from enum import Enum
from pydantic import BaseModel, Field

class RelationType(str, Enum):
    """
    Enumeration for graph edge relationship types between document elements.
    """
    STRUCTURAL = 'structural'
    SEMANTIC_SUPPORT = 'semantic_support'
    CAPTION_OF = 'caption_of'
    CROSS_REFERENCE = 'cross_reference'

class BaseDocumentElement(BaseModel):
    """
    Base class representing a generic element extracted from a document.
    """
    element_id: UUID = Field(
        ..., 
        description="A globally unique identifier for the document element."
    )
    page_number: int = Field(
        ..., 
        description="The page number where the document element is located."
    )
    bounding_box: Tuple[float, float, float, float] = Field(
        ..., 
        description="Tuple of coordinates (x0, y0, x1, y1) representing the element's bounding box."
    )
    raw_content: str = Field(
        ..., 
        description="The raw extracted content from the element (e.g., text, OCR output)."
    )

class TextElement(BaseDocumentElement):
    """
    Represents a textual element, such as a paragraph, heading, or footnote.
    """
    pass

class TitleElement(TextElement):
    """
    Represents a Title or Heading element.
    """
    pass

class TableElement(BaseDocumentElement):
    """
    Represents a structured table extracted from the document.
    """
    grid_format: str = Field(
        ..., 
        description="Markdown or HTML representation preserving the tabular grid structure."
    )

class ImageElement(BaseDocumentElement):
    """
    Represents an image, figure, or chart extracted from the document.
    """
    semantic_description: str = Field(
        ..., 
        description="A semantic description of the visual content generated by a Vision-Language Model."
    )

class GraphEdge(BaseModel):
    """
    Represents a directional relationship between two document elements in the knowledge graph.
    """
    source_id: UUID = Field(
        ..., 
        description="The UUID of the source document element."
    )
    target_id: UUID = Field(
        ..., 
        description="The UUID of the target document element."
    )
    relation_type: RelationType = Field(
        ..., 
        description="The specific type of semantic or structural relationship."
    )
